# Configuration for librarian-puppet. For example:
# 
forge "http://forge.puppetlabs.com"
# 
# mod "puppetlabs/razor"
# mod "puppetlabs/ntp", "0.0.3"
# 
# mod "apt",
#   :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
# 
# mod "stdlib",
#   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"
#
mod "elasticsearch",
    :git => "https://github.com/elasticsearch/puppet-elasticsearch.git"
mod "puppetlabs/java"
mod "python",
    :git => "https://github.com/stankevich/puppet-python"
mod "stahnma/epel"
    
mod "stdlib",
    :git => "https://github.com/puppetlabs/puppetlabs-stdlib.git"
mod "vcsrepo",
    :git => "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
mod "concat",
    :git => "https://github.com/puppetlabs/puppetlabs-concat.git"
